/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n8.1.2-50-g1a748fe2cd-20260905"
#endif /* AVUTIL_FFVERSION_H */
